#PBS -N regrid_test
#PBS -j n
#PBS -l select=2
#PBS -l walltime=00:20:00
#PBS -q short
#PBS -A n02-cms

# Make sure any symbolic links are resolved to absolute path
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)

# Change to the directory that the job was submitted from
cd $PBS_O_WORKDIR

XIOS_DIR=/work/n02/n02/jwc/XIOS/extract/xios_trunk_r1964
XIOS_EXEC=$XIOS_DIR/bin/xios_server.exe
MODEL_EXEC=./xios_test
INPUT_DATA_NML='input_data'
NPROCX=4
NPROCY=6
((NPROC=NPROCX*NPROCY))
NTIMES=1

LAUNCH_MPI_MODEL="-ss -n $NPROC -N 24 -S 12 -d 1 -j 1"
LAUNCH_MPI_XIOS="-ss -n 6 -N 6 -S 3 -d 1 -j 1"

# Create input namelist file
cat > xios_test.in << EOF
&input
  do_regrid = .TRUE.,
  do_ens = .FALSE.,
  infile_data_base = '$INPUT_DATA_NML',
  verbose = 1,
  write_output = .FALSE.,
  nprocx = $NPROCX,
  nprocy = $NPROCY,
  nt = $NTIMES,
  ncopies = 2
/

&input_regrid
  grid_type = 1,
  nlat_regrid = 96
/
EOF

# Create input data namelist file
cat > $INPUT_DATA_NML << EOF
&input_data
  filename = '../data/u_plev_192x145x17.nc',
  varname = 'u',
  varname_xios = 'u',
/
EOF

# Create XIOS xml file
cat > iodef.xml << EOF
<!-- Test XIOS regridding -->

<simulation>
  <context id="xios_test" >
    <axis_definition>
      <axis id="um-atmos_dp17" long_name="pressure levels" n_glo="17" name="dp17" positive="down" standard_name="air_pressure" unit="hPa" value="(0,16)[1000.000 925.000 850.000 700.000 600.000 500.000 400.000 300.000 250.000 200.000 150.000 100.000 70.000 50.000 30.000 20.000 10.000]" />
    </axis_definition>

    <domain_definition>
      <domain id="input_domain" name="in" />
      <domain id="regrid_domain" name="regrid" />
    </domain_definition>

    <grid_definition>
      <grid id="grid_in">
        <domain domain_ref="input_domain" />
        <axis axis_ref="um-atmos_dp17" />
      </grid>
      <grid id="grid_regrid">
        <domain domain_ref="regrid_domain">
          <interpolate_domain order="2" />
        </domain>
        <axis axis_ref="um-atmos_dp17" />
      </grid>
    </grid_definition>

    <field_definition default_value="-1073741824.0" prec="8" >
      <field id="u" grid_ref="grid_in" long_name="U COMPNT OF WIND ON P LEV/UV GRID" standard_name="eastward_wind" unit="m s-1" />
      <field id="u_regrid" field_ref="u" grid_ref="grid_regrid" />
    </field_definition>

    <!-- <file_definition format="netcdf4" time_counter="instant" type="multiple_file" > -->
    <file_definition format="netcdf4" time_counter="instant" type="one_file" >
      <file id="output" name="regrid_test" output_freq="1h">
        <field field_ref="u" operation="instant" />
        <field field_ref="u_regrid" operation="instant" />
      </file>
    </file_definition>
  </context>

  <context id="xios">
    <variable_definition>
      <variable id="using_server" type="bool">true</variable>
      <variable id="info_level" type="int">100</variable>
      <variable id="print_file" type="bool">true</variable>
    </variable_definition>
  </context>
</simulation>
EOF

APRUN_ARG="$LAUNCH_MPI_MODEL $MODEL_EXEC : $LAUNCH_MPI_XIOS $XIOS_EXEC"

echo "aprun $APRUN_ARG"
aprun $APRUN_ARG
